freebsd_13_task:
  freebsd_instance:
    image: freebsd-13-2-release-amd64
  install_script:
    pkg install -y cmake gnutls perl5
  build_script:
    - cmake .
    - make -j$(getconf _NPROCESSORS_ONLN)
  test_script:
      # run tests as user "cirrus" instead of root
    - pw useradd cirrus -m
    - chown -R cirrus:cirrus .
    - ctest -j$(getconf _NPROCESSORS_ONLN) --output-on-failure

macos_x_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  install_script:
    - brew update
    - brew install cmake gnutls zlib
  build_script:
    - cmake .
    - make -j$(getconf _NPROCESSORS_ONLN)
  test_script:
    ctest -j$(getconf _NPROCESSORS_ONLN) --output-on-failure

ubuntu_amd64_task:
  container:
    image: ubuntu:jammy
  install_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
    - DEBIAN_FRONTEND=noninteractive apt-get -y install cmake libgnutls28-dev libz-dev libhyperscan-dev valgrind
  build_script:
    - cmake .
    - make -j$(getconf _NPROCESSORS_ONLN)
  test_script:
    ctest -j$(getconf _NPROCESSORS_ONLN) --output-on-failure

debian_i386_task:
  container:
    image: debian:bookworm
  install_script:
    - dpkg --add-architecture i386
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
    - DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc-i686-linux-gnu libc6:i386 libgnutls28-dev:i386 libz-dev:i386
  build_script:
    - cmake -DCMAKE_C_COMPILER=i686-linux-gnu-gcc .
    - make -j$(getconf _NPROCESSORS_ONLN)
  test_script:
    ctest -j$(getconf _NPROCESSORS_ONLN) --output-on-failure

ubuntu_arm64_task:
  arm_container:
    image: ubuntu:jammy
  install_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
    - DEBIAN_FRONTEND=noninteractive apt-get -y install cmake libgnutls28-dev libz-dev valgrind libvectorscan-dev
  build_script:
    - cmake .
    - make -j$(getconf _NPROCESSORS_ONLN)
  test_script:
    ctest -j$(getconf _NPROCESSORS_ONLN) --output-on-failure

#ubuntu_armhf_task:
#  arm_container:
#    image: ubuntu:jammy
#  install_script:
#    - dpkg --add-architecture armhf
#    - apt-get update
#    - DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
#    - DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc-arm-linux-gnueabihf libc6:armhf libgnutls28-dev:armhf libz-dev:armhf
#  build_script:
#    - cmake -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc .
#    - make -j$(getconf _NPROCESSORS_ONLN)
#  test_script:
#    ctest -j$(getconf _NPROCESSORS_ONLN) --output-on-failure
