language: c
matrix:
  include:
    - os: linux
      arch: amd64
      dist: xenial
      addons:
        apt:
          packages:
          - libz-dev
          - libgnutls28-dev
          - cmake
    - os: linux
      arch: ppc64le
      dist: xenial
      addons:
        apt:
          packages:
          - libz-dev
          - libgnutls28-dev
          - cmake
      before_install: sudo apt update
    - os: linux
      arch: amd64
      dist: focal
      addons:
        apt:
          packages:
          - libz-dev
          - libgnutls28-dev
          - cmake
    - os: linux
      arch: ppc64le
      dist: focal
      addons:
        apt:
          packages:
          - libz-dev
          - libgnutls28-dev
          - cmake
      before_install: sudo apt update && sudo apt install -y gettext;
    #Travis runs for FruitOS cost >25× as much as anything else.
    #- os: osx
    #  osx_image: xcode12.2
    #  before_install:
    #    brew update && for pkg in libtool glib gettext;do if ! brew list -1|grep -q "^${pkg}\$";then brew install "$pkg";fi;done && brew link --force gettext

script: cmake . && make -j$(getconf _NPROCESSORS_ONLN)
test_script: ctest -j$(getconf _NPROCESSORS_ONLN) --output-on-failure
