#!/bin/sh

v=`git describe 2>/dev/null`
test -n "$v" || v=`cat VERSION` || v=UNKNOWN

[ ! -d .git ] || ! which git >/dev/null || { git diff-index --quiet HEAD -- || v="$v-dirty"; }

[ "$1" != "-n" ] || n=-n
echo $n "${v##v}"
