#!/bin/sh
set -e

DIR="$1"
shift
DIR="${*:+${DIR:-.}/}"

mkdir -p "protos"

for f in ${*:--}
  do
    h="${f%.cc}.h"
    (cd "$DIR";
    # functions
    grep -Eh '^[a-zA-Z_]+.*[a-zA-Z_][a-zA-Z0-9_]*\(.*\)$' "$f"|
    grep -v '^static'|
    grep -Ev '^[^(]*::'|
    grep -Ev '^void [a-z_]+_command\('|
    grep -Ev '^session \*[a-z_]+_command\('|
    sed 's/.*/extern &;/'

    # variables
    grep -Eh '^[a-zA-Z_][][a-zA-Z0-9_*, ]*[=;]' "$f"|
    grep -v '^static'|
    grep -v '^extern'|
    grep -v '^typedef'|
    sed 's/ *[=;].*//'|
    sed 's/.*/extern &;/'

    # function pointers
    grep -Eh '^[a-zA-Z_]+ \(\*[a-zA-Z_]+\)\([][a-zA-Z0-9_*,. ]*\) *[=;]' "$f"|
    grep -v '^static'|
    grep -v '^extern'|
    grep -v '^typedef'|
    sed 's/ *[=;].*//'|
    sed 's/.*/extern &;/'
    ) >"protos/$h"
  done
