name: Coverity scan

on:
  push:
    branches: [coverity]

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - name: Update apt
      run: sudo apt-get update -qq
    - name: Install dependencies
      run: sudo apt-get install -y
               cmake
               libgnutls28-dev
               libz-dev
               libhyperscan-dev
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake -B ${{github.workspace}}/build
    - uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        command: make -C ${{github.workspace}}/build
